{
 "title": "MSMQ w/ Powershell",
 "description": "use with custom msmq-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "machine_name",
    "label": "Machine Name",
    "query": {
     "query": "label_values(msmq_queue_message_count,machine_name)"
    }
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": {
     "query": "label_values(msmq_queue_message_count{machine_name=~\"$machine_name\"},queue_name)"
    }
   },
   {
    "name": "outgoing_queue_name",
    "label": "Outgoing Queue Name",
    "query": {
     "query": "label_values(msmq_outgoing_queue_message_count{connection_host=~\"$machine_name\"},queue_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MSMQ - Number of Messages",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "msmq_queue_message_count{job=\"msmq_exporter\", machine_name=~\"$machine_name\", queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "MSMQ - Bytes in Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "msmq_queue_bytes_in_queue{job=\"msmq_exporter\", machine_name=~\"$machine_name\", queue_name=~\"$queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  { "title": "Outgoing Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "MSMQ - Outgoing - Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "msmq_outgoing_queue_state{job=\"msmq_exporter\", connection_host=~\"$machine_name\", queue_name=~\"$outgoing_queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "MSMQ - Outgoing - Unprocessed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "msmq_outgoing_queue_unprocessed_message_count{job=\"msmq_exporter\", connection_host=~\"$machine_name\", queue_name=~\"$outgoing_queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "MSMQ - Outgoing - Number of Messages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "msmq_outgoing_queue_message_count{job=\"msmq_exporter\", connection_host=~\"$machine_name\", queue_name=~\"$outgoing_queue_name\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "MSMQ - Outgoing - Bytes in Messages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "msmq_outgoing_queue_bytes_in_queue{connection_host=~\"$machine_name\", job=\"msmq_exporter\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}