{
 "title": "MSMQ v2",
 "description": "use with custom msmq-exporter-v2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "machine_name",
    "label": "Machine Name",
    "query": {
     "query": "label_values(msmq_queue_message_count{job=\"msmq_exporter_v2\"},machine_name)"
    }
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": {
     "query": "label_values(msmq_queue_message_count{machine_name=~\"$machine_name\", job=\"msmq_exporter_v2\"},queue_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MSMQ - Number of Messages",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "msmq_queue_message_count{job=\"msmq_exporter_v2\", machine_name=~\"$machine_name\", queue_name!~\"^os:.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "MSMQ - Bytes in Queue",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "msmq_queue_bytes_in_queue{job=\"msmq_exporter_v2\", machine_name=~\"$machine_name\", queue_name!~\"^os:.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "MSMQ - Number of Messages - Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "msmq_queue_message_count{job=\"msmq_exporter_v2\", machine_name=~\"$machine_name\", queue_name=~\"^os:.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "MSMQ - Bytes in Queue - Outgoing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "msmq_queue_bytes_in_queue{job=\"msmq_exporter_v2\", machine_name=~\"$machine_name\", queue_name=~\"^os:.*\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}